<a href="https://colab.research.google.com/github/NiharikaKomaragiri/Python-Course-Work/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
#Different arrays

arr1=np.array([1,2,3,4,5])
print('1-dim',arr1,sep='\n',end='\n\n')

arr2=np.array([[1,2,6],[3,4,5]])
print('2-dim',arr2,sep='\n',end='\n\n')

arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print('multi-dim',arr3,sep='\n',end='\n\n')

1-dim
[1 2 3 4 5]

2-dim
[[1 2 6]
 [3 4 5]]

multi-dim
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]



In [5]:
zeros=np.zeros((5,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
ones=np.ones((7,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
identity=np.eye(5) #eye for identity matrix
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
Full_array=np.full((5,3),True) #full matrix is named as True
print(Full_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [9]:
Full_array=np.full((5,3),False) #full matrix is named as False
print(Full_array)

[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]]


In [10]:
range_arr=np.arange(3,21,3) #arrange in a range
print(range_arr)

[ 3  6  9 12 15 18]


In [11]:
lin_space=np.linspace(0,200,5) #linespace for dividing them into equal parts
print(lin_space)

[  0.  50. 100. 150. 200.]


In [12]:
rand_int=np.random.randint(30,60) # random number is displayed in the range given
print(rand_int)

36


In [13]:
rand_float=np.random.uniform(20,70)
print(rand_float)

43.30737797650214


In [14]:
rand_int=np.random.randint(1,6,(5,5))
print(rand_int)

[[4 4 4 3 2]
 [1 2 2 1 3]
 [3 1 1 5 3]
 [3 5 2 4 2]
 [5 1 1 3 2]]


In [15]:
rand_cho=np.random.choice(['html','css','java','python','javascript','mysql'],3)
print(rand_cho)


['javascript' 'python' 'html']


In [16]:
np.random.seed(10)
rand_cho=np.random.randint(6)
print(rand_cho)

1


In [17]:
arr=np.array([[1,2],[4,5],[6,7],[8,9],[10,11],[12,13],[14,15]])
print(arr.shape)

(7, 2)


In [18]:
reshaped=arr.reshape(2,7)
print(reshaped)

[[ 1  2  4  5  6  7  8]
 [ 9 10 11 12 13 14 15]]


In [19]:
a=np.array([[1,2,3,4],[1,2,3,4]])
#flattend
flat=a.flatten()
print(flat)

[1 2 3 4 1 2 3 4]


In [20]:
trans=arr.T
print(trans)

[[ 1  4  6  8 10 12 14]
 [ 2  5  7  9 11 13 15]]


In [21]:
arr=np.array([10,20,30,40,50])
#slicing
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:3])
print(arr[::2])

10
50
[20 30 40]
[10 20 30]
[10 30 50]


In [22]:
import numpy as np
#slicing of array it will diplay group of numbers
matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(matrix[0, 1])
print(matrix[1, 2])
print(matrix[2, 0])
print(matrix[0:3,0])
print(matrix[0:3,2])
print(matrix[0:3,0:3])
print(matrix[0:3,0:2])

2
6
7
[1 4 7]
[3 6 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]


In [23]:
arr=np.array([4,9,16,25,36])


In [24]:
#in arrays we need not to iterate the data we can directly add to the variable
print(arr+1)
print(arr-1)
print(arr*2)
print(arr**2)
print(np.sqrt(arr))

[ 5 10 17 26 37]
[ 3  8 15 24 35]
[ 8 18 32 50 72]
[  16   81  256  625 1296]
[2. 3. 4. 5. 6.]


In [25]:
print(np.sum(arr)) #sum
print(np.mean(arr)) #mean
print(np.median(arr)) #median

90
18.0
16.0


In [26]:
print(np.mean(arr)) #Mean
print(np.var(arr)) #variance
print(np.std(arr)) #standard deviation

18.0
130.8
11.436782764396638


In [27]:
print(np.min(arr))
print(np.max(arr))

4
36


In [28]:
arr=np.array([1,2,3,4,5])
print(np.cumsum(arr)) #cumulative sum
print(np.cumprod(arr))#cumulative product

[ 1  3  6 10 15]
[  1   2   6  24 120]


In [29]:
arr=np.array([10,20,30,40,50])
print(arr>=30)
print(arr[arr>=30])

[False False  True  True  True]
[30 40 50]


In [30]:
arr=np.array([10,20,30,40,50])
s=np.sort(arr)
print(s)

[10 20 30 40 50]


In [31]:
arr=np.array([10,20,30,40,50,50,40])
unique=np.unique(arr)
print(unique)

[10 20 30 40 50]


In [32]:
arr = np.array([10, 20, 30, 40, 50])
# Boolean indexing
bool_arr = arr > 25
print(bool_arr) # Returns [False, False, True, True, True]
# Filtering values
filtered_arr = arr[arr > 25]
print(filtered_arr) # Returns [30, 40, 50]

[False False  True  True  True]
[30 40 50]


In [40]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


In [39]:
# Matrix multiplication
print(np.dot(A, B))

# Determinant
print(np.linalg.det(A))

# Inverse
print(np.linalg.inv(A))

[[19 22]
 [43 50]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [37]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)


[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [41]:
# Solving linear equations (Ax = B)
C = np.array([5, 11])
solution = np.linalg.solve(A, C)
print(solution)

[1. 2.]


In [42]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
# Sorting an array
sorted_arr = np.sort(arr)
print(sorted_arr)
# Unique elements
unique_vals = np.unique(arr)
print(unique_vals)

[1 1 2 3 4 5 6 9]
[1 2 3 4 5 6 9]


In [43]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


In [44]:
# Stacking arrays vertically and horizontally
vertical_stack = np.vstack((A, B))
horizontal_stack = np.hstack((A, B))
print(vertical_stack)
print(horizontal_stack)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [45]:
# Splitting arrays
split_arr = np.split(np.array([1, 2, 3, 4, 5, 6]), 3)
print(split_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [46]:
arr = np.array([10, 20, 30])
# Shallow copy (view)
view_arr = arr.view()
view_arr[0] = 100
print(arr) # Changes reflect in original array

[100  20  30]


In [47]:
# Deep copy
copy_arr = arr.copy()
copy_arr[0] = 200
print(arr) # Original array remains unchanged

[100  20  30]
